In [5]:
A=10000
B=12
C=A/B
if C>500:
    d=True
else:
    d=False
print(d)

True


In [7]:
TOTAL_AMOUNT=10000
VALUE_OF_ONE_ITEM=12
MONEY_NEEDED=TOTAL_AMOUNT/VALUE_OF_ONE_ITEM
if MONEY_NEEDED>500:
    PURCHASE=True
else:
    PURCHASE=False
print("PURCHASE=",PURCHASE)

PURCHASE= True


In [ ]:
#Mart_Store 
print("Hello!!Welcome to SMS Mart")
GST = 18 
categories = {

"Veggies": [ {"name": "SPINACH", "amount": 32.00, "discount": 2}, {"name":"Mango", "amount":120, "discount":10}],
"Beauty": [ {"name": "Maskara", "amount": 320, "discount": 35}, {"name":"Lipstick", "amount":750, "discount":25}],
"Electronics": [ {"name": "GPU", "amount": 5600, "discount": 275}, {"name":"RGB", "amount":3575, "discount":75}],
"Grocery": [ {"name": "Pulses", "amount": 200, "discount": 15}, {"name":"Kidney Beans", "amount":375, "discount":5}],
"Stationary": [ {"name": "Copy", "amount": 100, "discount": 5}, {"name":"Clay", "amount":75, "discount":2} ],
"Furniture": [ {"name": "Chair", "amount": 15600, "discount": 2115}, {"name":"Table", "amount":13575, "discount":1725}] 

} 
for category, products in categories.items():
    print(f"category={category}")

for product in products:
    amount = product["amount"] 
    discount = product["discount"] 
    discount_price = amount - discount 
    gst_amount = discount_price * GST / 100 
    actual_amount = discount_price + gst_amount 


    print(f"Product: {product['name']}") 
    print(f"Original Amount: ₹{amount:}") 
    print(f"Discount: ₹{discount:}") 
    print(f"Discounted Price: ₹{discount_price:}") 
    print(f"GST: ₹{gst_amount:}") 
    print(f"Final Amount: ₹{actual_amount:}")





Hello!!Welcome to SMS Mart
category=Veggies
category=Beauty
category=Electronics
category=Grocery
category=Stationary
category=Furniture
Product: Chair
Original Amount: ₹15600
Discount: ₹2115
Discounted Price: ₹13485
GST: ₹2427.3
Final Amount: ₹15912.3
Product: Table
Original Amount: ₹13575
Discount: ₹1725
Discounted Price: ₹11850
GST: ₹2133.0
Final Amount: ₹13983.0


In [6]:
import numpy as np
aray = np.array([[['A', 'B', 'C'],['D', 'E','F'],['G', 'H','I']]
                ,[['J', 'K', 'L'], ['M','N','O'],['P', 'Q', 'R']]
                ,[['S', 'T', 'U'], ['V','W','X'],['Y', 'Z','']]])
word = aray[0, 0, 0]+aray[2, 0, 0]+aray[2, 0, 0]
word1=aray[0,1,0]+aray[0,0,0]+aray[2,0,2]
print(word)
print(word1)
print(aray)
print(aray.ndim)
print(aray.shape)
print(array)
print(array.ndim)
print(array.shape)

ASS
DAU
[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' '']]]
3
(3, 3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [10]:
import numpy as np 
arr_1=np.array([[1,2,3,4],[7,8,9,1],[0,1,2,5],[5,6,4,3]])
print(arr_1.ndim)
print(arr_1.shape)
arr_2=np.array([[5],[6],[7],[8]])
print(arr_2.ndim)
print(arr_2.shape)
print(arr_1*arr_2)
arr_3=np.array([[10,11,13],[100,110,300]])
print(arr_3.ndim)

2
(4, 4)
2
(4, 1)
[[ 5 10 15 20]
 [42 48 54  6]
 [ 0  7 14 35]
 [40 48 32 24]]
2
